name: Build and Deploy Code

on:

jobs:
  # testing only
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: testing github actions for CI/CD
      - run: echo "Learning CI/CD sample!!"

  # CI/CD pipeline config - deployment
  # job1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: pulling git repo
  #       uses: actions/checkout@v3
  #     - name: install python version 3.11.1
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.11.1'
  #     - name: update pip
  #       run: python -m pip install --upgrade pip
  #     - name: install all dependencies
  #       run: pip install -r requirements.txt
  #     - name: test with pytest
  #       run:
  #         pip install pytest
  #         pytest -v -s
